### ISSUE TITLE
KLA json

### ISSUE THREAD

**Issue by iandoug** [PanicJoker03/antithesis-layout#1]
Hi

Can you please post the KLA json?

Thanks, Ian

**Comment by PanicJoker03** [comment]
Hello,
I had just pushed a commit with the json layout. Please, make a pull to confirm the changes.

**Comment by PanicJoker03** [comment]
Hello, let me share the link to the json:
https://github.com/PanicJoker03/antithesis-layout/blob/main/ant%C3%ADtesis%20analysis%20definition.json

Have a nice day!

**Comment by iandoug** [comment]
Thanks, working. I expect to add it over the weekend. :-)
